/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;


import java.awt.Dimension;


/**
 *
 * @author SARA
 */
public class Barranquilla extends javax.swing.JFrame {

    /**
     * Creates new form Barranquilla
     */
    public Barranquilla() {
        initComponents();
        setMinimumSize(new Dimension(740, 540));
        setSize(740, 540); // o el tamaño que prefieras
        setLocationRelativeTo(null); // centra la ventana
        setVisible(true); // asegura que se vea al abrirla

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ReservarBPlaza = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ReservarWindsor = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ReservarCountry = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(755, 483));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Barranquilla Plaza  (1).jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 0, 140, 130);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setText("Hotel Barranquilla plaza ");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(150, 50, 190, 20);

        ReservarBPlaza.setBackground(new java.awt.Color(0, 204, 204));
        ReservarBPlaza.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        ReservarBPlaza.setText("Reservar");
        ReservarBPlaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservarBPlazaActionPerformed(evt);
            }
        });
        jPanel2.add(ReservarBPlaza);
        ReservarBPlaza.setBounds(565, 50, 110, 27);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 10, 690, 130);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/windsorbarranquilla (1).jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(0, 0, 140, 130);

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel5.setText("Hotel Windsor Barranquilla ");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(150, 50, 210, 20);

        ReservarWindsor.setBackground(new java.awt.Color(0, 204, 204));
        ReservarWindsor.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        ReservarWindsor.setText("Reservar");
        ReservarWindsor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservarWindsorActionPerformed(evt);
            }
        });
        jPanel3.add(ReservarWindsor);
        ReservarWindsor.setBounds(570, 50, 100, 24);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 150, 690, 130);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Country (1).jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(0, 0, 140, 130);

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel7.setText("Country International Hotel");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(150, 60, 210, 20);

        ReservarCountry.setBackground(new java.awt.Color(0, 204, 204));
        ReservarCountry.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        ReservarCountry.setText("Reservar");
        ReservarCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservarCountryActionPerformed(evt);
            }
        });
        jPanel4.add(ReservarCountry);
        ReservarCountry.setBounds(575, 50, 100, 27);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(10, 290, 690, 130);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 40, 710, 430);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setText("Seleccione El Hotel Donde Desea Hacer Su Reserva");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 0, 510, 25);

        jButton4.setBackground(new java.awt.Color(0, 204, 255));
        jButton4.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Regresar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(10, 480, 100, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reserva.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 0, 50, 32);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReservarBPlazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservarBPlazaActionPerformed
        // TODO add your handling code here:
        new RegisTuristaHotel().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ReservarBPlazaActionPerformed

    private void ReservarCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservarCountryActionPerformed
        // TODO add your handling code here:
        new RegisTuristaHotel().setVisible(true);
        
    }//GEN-LAST:event_ReservarCountryActionPerformed

    private void ReservarWindsorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservarWindsorActionPerformed
        // TODO add your handling code here:
        new RegisTuristaHotel().setVisible(true);
    }//GEN-LAST:event_ReservarWindsorActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new Principal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Barranquilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Barranquilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Barranquilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Barranquilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Barranquilla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ReservarBPlaza;
    private javax.swing.JButton ReservarCountry;
    private javax.swing.JButton ReservarWindsor;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
