/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package UI;

import DAO.ReservaDAO;
import java.lang.String;
import javax.swing.JOptionPane;
import java.util.Date;
import Modelo.Reserva;
import Datos.GestorReservas;
import UI.Barranquilla;
import UI.MisReservas;
import com.google.gson.Gson;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.List;


/**
 *
 * @author Administrator
 */
public class RegisTuristaHotel extends javax.swing.JFrame {

    /**
     * Creates new form RegisTuristaHotelBarranquillaPlaza
     */
    public RegisTuristaHotel() {
        initComponents();
        setMinimumSize(new Dimension(740, 540));
        setSize(740, 540); // o el tamaño que prefieras
        setLocationRelativeTo(null); // centra la ventana
        setVisible(true); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cbxTipoId = new javax.swing.JComboBox<>();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtDocumento = new javax.swing.JTextField();
        cbxLugar = new javax.swing.JComboBox<>();
        txtHabitaciones = new javax.swing.JTextField();
        jCalendarCheckIn = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jCalendarCheckOut = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbxNumeroHabitacion = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        txtCantidadPersonas = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Guardar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setText("Ingrese sus Datos Para Realizar Su Reserva");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 10, 400, 16);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        cbxTipoId.setBackground(new java.awt.Color(204, 204, 204));
        cbxTipoId.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        cbxTipoId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "C.C", "N.I.T", "Pasaporte", "Licencia De Conducir" }));
        jPanel1.add(cbxTipoId);
        cbxTipoId.setBounds(20, 120, 180, 26);

        txtNombres.setBackground(new java.awt.Color(204, 204, 204));
        txtNombres.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jPanel1.add(txtNombres);
        txtNombres.setBounds(20, 40, 180, 22);

        txtApellidos.setEditable(false);
        txtApellidos.setBackground(new java.awt.Color(204, 204, 204));
        txtApellidos.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jPanel1.add(txtApellidos);
        txtApellidos.setBounds(20, 80, 180, 22);

        txtDocumento.setBackground(new java.awt.Color(204, 204, 204));
        txtDocumento.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jPanel1.add(txtDocumento);
        txtDocumento.setBounds(20, 170, 180, 22);

        cbxLugar.setBackground(new java.awt.Color(204, 204, 204));
        cbxLugar.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        cbxLugar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Habitacion", "Penthouse", "Salon de Eventos", "Restaurante", " " }));
        jPanel1.add(cbxLugar);
        cbxLugar.setBounds(20, 210, 200, 26);

        txtHabitaciones.setBackground(new java.awt.Color(204, 204, 204));
        txtHabitaciones.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jPanel1.add(txtHabitaciones);
        txtHabitaciones.setBounds(320, 90, 200, 20);
        jPanel1.add(jCalendarCheckIn);
        jCalendarCheckIn.setBounds(320, 180, 90, 22);

        jLabel7.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Check In:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(320, 160, 80, 20);

        jLabel8.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Check Out:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(320, 200, 90, 20);
        jPanel1.add(jCalendarCheckOut);
        jCalendarCheckOut.setBounds(320, 220, 90, 22);

        jLabel3.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 20, 100, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Apellido:");
        jLabel4.setToolTipText("");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 60, 80, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tipo ID:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 100, 70, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Numero ID:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 150, 110, 20);

        jLabel9.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Lugar reserva:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 190, 120, 20);

        jLabel10.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Numero de Habitaciones:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(320, 70, 190, 20);

        jLabel11.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Numero de Habitacion:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(320, 110, 180, 20);

        cbxNumeroHabitacion.setBackground(new java.awt.Color(204, 204, 204));
        cbxNumeroHabitacion.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        cbxNumeroHabitacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "101", "102", "103", "104", "105", "106", "107", "108", "109", "110", " " }));
        jPanel1.add(cbxNumeroHabitacion);
        cbxNumeroHabitacion.setBounds(320, 130, 200, 26);

        jLabel12.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Cantidad de Personas:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(320, 30, 150, 20);

        txtCantidadPersonas.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txtCantidadPersonas);
        txtCantidadPersonas.setBounds(320, 50, 200, 22);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Fondo (4).jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 530, 260);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 40, 530, 260);

        jButton3.setBackground(new java.awt.Color(0, 204, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Regresar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(0, 350, 90, 27);

        jButton1.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 51, 51));
        jButton1.setText("Vaciar");
        getContentPane().add(jButton1);
        jButton1.setBounds(180, 310, 72, 27);

        Guardar.setBackground(new java.awt.Color(0, 255, 153));
        Guardar.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        getContentPane().add(Guardar);
        Guardar.setBounds(290, 310, 90, 27);

        jButton2.setText("Reportar error");
        getContentPane().add(jButton2);
        jButton2.setBounds(470, 340, 103, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // TODO add your handling code here:
    Gson gson = new Gson();

    // Obtener datos del formulario
    String nombres = txtNombres.getText();
    String apellidos = txtApellidos.getText();
    String tipoId = (String) cbxTipoId.getSelectedItem();
    String documento = txtDocumento.getText();
    String lugar = (String) cbxLugar.getSelectedItem();
    Date fechaCheckIn = jCalendarCheckIn.getDate();
    Date fechaCheckOut = jCalendarCheckOut.getDate();
    int cantidadPersonas = Integer.parseInt(txtCantidadPersonas.getText());
    int habitaciones = Integer.parseInt(txtHabitaciones.getText());
    String numeroHabitacionStr = (String) cbxNumeroHabitacion.getSelectedItem();

    // Validar valores positivos
    if (cantidadPersonas <= 0 || habitaciones <= 0) {
        JOptionPane.showMessageDialog(this, "La cantidad de personas y habitaciones debe ser un número positivo.");
        return;
    }

    // Validar máximo de habitaciones según cantidad de personas
    int maxHabitaciones = 0;
    if (cantidadPersonas <= 4) {
        maxHabitaciones = 1;
    } else if (cantidadPersonas <= 8) {
        maxHabitaciones = 2;
    } else if (cantidadPersonas <= 12) {
        maxHabitaciones = 3;
    } else {
        JOptionPane.showMessageDialog(this, "No se permiten reservas para más de 12 personas.");
        return;
    }

    if (habitaciones > maxHabitaciones) {
        JOptionPane.showMessageDialog(this, "Para " + cantidadPersonas + " personas solo se permiten hasta " + maxHabitaciones + " habitaciones.");
        return;
    }

    // Validar que la habitación no esté reservada para las fechas seleccionadas
    ReservaDAO gestor = new ReservaDAO();
    if (gestor.habitacionYaReservada(numeroHabitacionStr, fechaCheckIn, fechaCheckOut)) {
        JOptionPane.showMessageDialog(this, "¡La habitación " + numeroHabitacionStr + " ya está reservada para esas fechas!");
        return;
    }

    // Crear objeto Reserva con todos los datos
    Reserva nuevaReserva = new Reserva(
        nombres,
        apellidos,
        tipoId,
        documento,
        lugar,
        numeroHabitacionStr,
        fechaCheckIn,
        fechaCheckOut,
        cantidadPersonas,
        habitaciones
    );

    // Guardar la reserva en archivo JSON
    gestor.agregarReserva(nuevaReserva);

    // Actualizar tabla de reservas si está abierta
    if (MisReservas.instanciaActiva != null) {
        MisReservas.instanciaActiva.cargarReservasEnTabla();
    }

    // Mensaje de éxito
    JOptionPane.showMessageDialog(this, "Reserva guardada exitosamente.");
    }//GEN-LAST:event_GuardarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new Barranquilla().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisTuristaHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisTuristaHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisTuristaHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisTuristaHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisTuristaHotel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Guardar;
    private javax.swing.JComboBox<String> cbxLugar;
    private javax.swing.JComboBox<String> cbxNumeroHabitacion;
    private javax.swing.JComboBox<String> cbxTipoId;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jCalendarCheckIn;
    private com.toedter.calendar.JDateChooser jCalendarCheckOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCantidadPersonas;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtHabitaciones;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
}
