/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Charts.GraficoDashboard;
import Charts.GraficoPastelDashboard;
import org.jfree.chart.ChartPanel;
import java.awt.BorderLayout;


/**
 *
 * @author Administrator
 */
public class Ventana_Admin extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Admin
     */
    public Ventana_Admin() {
        initComponents();
        
    GraficoDashboard gd = new GraficoDashboard();
    ChartPanel cp = gd.crearPanelGraficoReservas();

    panelgrafico.setLayout(new BorderLayout());
    panelgrafico.add(cp, BorderLayout.CENTER);
    panelgrafico.validate();
    
    GraficoPastelDashboard gpd = new GraficoPastelDashboard();
    ChartPanel cpPastel = gpd.crearPanelGraficoPastel();

    panelgrafico2.setLayout(new BorderLayout());
    panelgrafico2.add(cpPastel, BorderLayout.CENTER);
    panelgrafico2.validate();



        
        
    }
    
   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblUsuariosNum = new javax.swing.JLabel();
        lblUsuariosTitulo = new javax.swing.JLabel();
        lblRegistrosNum = new javax.swing.JLabel();
        lblRegistrosTitulo = new javax.swing.JLabel();
        lblingresosNum = new javax.swing.JLabel();
        lblIngresosTitulo = new javax.swing.JLabel();
        lblUsuariosNuevosNum = new javax.swing.JLabel();
        lblUsuariosNuevosTitulo = new javax.swing.JLabel();
        panelgrafico = new javax.swing.JPanel();
        panelgrafico2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        PanelDashboard = new javax.swing.JButton();
        PanelReservas = new javax.swing.JButton();
        PanelHabitaciones = new javax.swing.JButton();
        PanelUsuarios = new javax.swing.JButton();
        PanelReportes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsuariosNum.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblUsuariosNum.setText("   0");
        jPanel2.add(lblUsuariosNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, 80));

        lblUsuariosTitulo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblUsuariosTitulo.setText("Usuarios registrados");
        jPanel2.add(lblUsuariosTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 110, -1));

        lblRegistrosNum.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblRegistrosNum.setText("   0");
        jPanel2.add(lblRegistrosNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 80, 80));

        lblRegistrosTitulo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblRegistrosTitulo.setText("Total Registros");
        jPanel2.add(lblRegistrosTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

        lblingresosNum.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblingresosNum.setText("   0");
        jPanel2.add(lblingresosNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 80, 80));

        lblIngresosTitulo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblIngresosTitulo.setText("Total Ingresos");
        jPanel2.add(lblIngresosTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, -1, -1));

        lblUsuariosNuevosNum.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblUsuariosNuevosNum.setText("   0");
        jPanel2.add(lblUsuariosNuevosNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 80, 80));

        lblUsuariosNuevosTitulo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblUsuariosNuevosTitulo.setText("Usuarios Nuevos del Mes");
        jPanel2.add(lblUsuariosNuevosTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 530, 120));

        panelgrafico.setBackground(new java.awt.Color(255, 255, 255));
        panelgrafico.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                panelgraficoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        panelgrafico.setLayout(new java.awt.BorderLayout());
        getContentPane().add(panelgrafico, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 270, 270));

        panelgrafico2.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(panelgrafico2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 260, 270));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelDashboard.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        PanelDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home (1).png"))); // NOI18N
        PanelDashboard.setText("  Dashboard");
        PanelDashboard.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        PanelDashboard.setContentAreaFilled(false);
        PanelDashboard.setFocusPainted(false);
        PanelDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PanelDashboardActionPerformed(evt);
            }
        });
        jPanel4.add(PanelDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 130, 50));

        PanelReservas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        PanelReservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/restaurant.png"))); // NOI18N
        PanelReservas.setText("    Reservas");
        PanelReservas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        PanelReservas.setContentAreaFilled(false);
        PanelReservas.setFocusPainted(false);
        PanelReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PanelReservasActionPerformed(evt);
            }
        });
        jPanel4.add(PanelReservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 140, 50));

        PanelHabitaciones.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        PanelHabitaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bed.png"))); // NOI18N
        PanelHabitaciones.setText(" Habitaciones");
        PanelHabitaciones.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        PanelHabitaciones.setContentAreaFilled(false);
        PanelHabitaciones.setFocusPainted(false);
        PanelHabitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PanelHabitacionesActionPerformed(evt);
            }
        });
        jPanel4.add(PanelHabitaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 140, 50));

        PanelUsuarios.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        PanelUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/users_group_customers_clients_icon-icons.com_72448.png"))); // NOI18N
        PanelUsuarios.setText("   Usuarios");
        PanelUsuarios.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        PanelUsuarios.setContentAreaFilled(false);
        PanelUsuarios.setFocusPainted(false);
        PanelUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PanelUsuariosActionPerformed(evt);
            }
        });
        jPanel4.add(PanelUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 140, 50));

        PanelReportes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        PanelReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/chart.png"))); // NOI18N
        PanelReportes.setText("   Reportes");
        PanelReportes.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        PanelReportes.setContentAreaFilled(false);
        PanelReportes.setFocusPainted(false);
        PanelReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PanelReportesActionPerformed(evt);
            }
        });
        jPanel4.add(PanelReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 140, 50));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PanelDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PanelDashboardActionPerformed
        // TODO add your handling code here:
        PanelDashboard.setBorder(null);             // elimina cualquier borde
        PanelDashboard.setBorderPainted(false);     // evita que el borde se pinte
        PanelDashboard.setFocusPainted(false);      // elimina el borde azul de enfoque
        PanelDashboard.setContentAreaFilled(false); // fondo transparente
        PanelDashboard.setOpaque(false);            // evita que se pinte un fondo solido
        PanelDashboard.setFocusable(false);         // evita que reciba enfoque y muestre líneas
        PanelDashboard.setFocusable(false);



    }//GEN-LAST:event_PanelDashboardActionPerformed

    private void PanelReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PanelReservasActionPerformed
        // TODO add your handling code here:
        PanelReservas.setBorder(null);             // elimina cualquier borde
        PanelReservas.setBorderPainted(false);     // evita que el borde se pinte
        PanelReservas.setFocusPainted(false);      // elimina el borde azul de enfoque
        PanelReservas.setContentAreaFilled(false); // fondo transparente
        PanelReservas.setOpaque(false);            // evita que se pinte un fondo solido
        PanelReservas.setFocusable(false);         // evita que reciba enfoque y muestre líneas
        PanelReservas.setFocusable(false);
    }//GEN-LAST:event_PanelReservasActionPerformed

    private void PanelHabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PanelHabitacionesActionPerformed
        // TODO add your handling code here:
        PanelHabitaciones.setBorder(null);             // elimina cualquier borde
        PanelHabitaciones.setBorderPainted(false);     // evita que el borde se pinte
        PanelHabitaciones.setFocusPainted(false);      // elimina el borde azul de enfoque
        PanelHabitaciones.setContentAreaFilled(false); // fondo transparente
        PanelHabitaciones.setOpaque(false);            // evita que se pinte un fondo solido
        PanelHabitaciones.setFocusable(false);         // evita que reciba enfoque y muestre líneas
        PanelHabitaciones.setFocusable(false);
    }//GEN-LAST:event_PanelHabitacionesActionPerformed

    private void PanelUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PanelUsuariosActionPerformed
        // TODO add your handling code here:
        PanelUsuarios.setBorder(null);             // elimina cualquier borde
        PanelUsuarios.setBorderPainted(false);     // evita que el borde se pinte
        PanelUsuarios.setFocusPainted(false);      // elimina el borde azul de enfoque
        PanelUsuarios.setContentAreaFilled(false); // fondo transparente
        PanelUsuarios.setOpaque(false);            // evita que se pinte un fondo solido
        PanelUsuarios.setFocusable(false);         // evita que reciba enfoque y muestre líneas
        PanelUsuarios.setFocusable(false);
    }//GEN-LAST:event_PanelUsuariosActionPerformed

    private void PanelReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PanelReportesActionPerformed
        // TODO add your handling code here:
        PanelReportes.setBorder(null);             // elimina cualquier borde
        PanelReportes.setBorderPainted(false);     // evita que el borde se pinte
        PanelReportes.setFocusPainted(false);      // elimina el borde azul de enfoque
        PanelReportes.setContentAreaFilled(false); // fondo transparente
        PanelReportes.setOpaque(false);            // evita que se pinte un fondo solido
        PanelReportes.setFocusable(false);         // evita que reciba enfoque y muestre líneas
        PanelReportes.setFocusable(false);
    }//GEN-LAST:event_PanelReportesActionPerformed

    private void panelgraficoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_panelgraficoAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_panelgraficoAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PanelDashboard;
    private javax.swing.JButton PanelHabitaciones;
    private javax.swing.JButton PanelReportes;
    private javax.swing.JButton PanelReservas;
    private javax.swing.JButton PanelUsuarios;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblIngresosTitulo;
    private javax.swing.JLabel lblRegistrosNum;
    private javax.swing.JLabel lblRegistrosTitulo;
    private javax.swing.JLabel lblUsuariosNuevosNum;
    private javax.swing.JLabel lblUsuariosNuevosTitulo;
    private javax.swing.JLabel lblUsuariosNum;
    private javax.swing.JLabel lblUsuariosTitulo;
    private javax.swing.JLabel lblingresosNum;
    private javax.swing.JPanel panelgrafico;
    private javax.swing.JPanel panelgrafico2;
    // End of variables declaration//GEN-END:variables
}
