/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import java.awt.CardLayout;
import UI.Panels.PanelDashboard;
import UI.Panels.PanelReservas;
import UI.Panels.PanelUsuarios;
import UI.Panels.PanelHabitaciones;
import UI.Panels.PanelReportes;




/**
 *
 * @author Administrator
 */
public class Ventana_Admin extends javax.swing.JFrame {
    
    private CardLayout cardLayout;

    /**
     * Creates new form Ventana_Admin
     */
    public Ventana_Admin() {
        initComponents();
        
       // Crear instancias de cada panel
    PanelDashboard dashboard = new PanelDashboard();
    PanelReservas reservas = new PanelReservas();
    PanelUsuarios usuarios = new PanelUsuarios();
    PanelHabitaciones habitaciones = new PanelHabitaciones();
    PanelReportes reportes = new PanelReportes();

    // Configurar CardLayout
    cardLayout = new CardLayout();
    panelContenedor.setLayout(cardLayout);

    // Agregar paneles
    panelContenedor.add(dashboard, "dashboard");
    panelContenedor.add(reservas, "reservas");
    panelContenedor.add(usuarios, "usuarios");
    panelContenedor.add(habitaciones, "habitaciones");
    panelContenedor.add(reportes, "reportes");

    // Mostrar por defecto el dashboard
    cardLayout.show(panelContenedor, "dashboard");
}
    
   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JButton();
        btnReservas = new javax.swing.JButton();
        btnHabitaciones = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        panelContenedor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDashboard.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home (1).png"))); // NOI18N
        btnDashboard.setText("  Dashboard");
        btnDashboard.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnDashboard.setContentAreaFilled(false);
        btnDashboard.setFocusPainted(false);
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });
        jPanel4.add(btnDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 140, 50));

        btnReservas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnReservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/restaurant.png"))); // NOI18N
        btnReservas.setText("    Reservas");
        btnReservas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnReservas.setContentAreaFilled(false);
        btnReservas.setFocusPainted(false);
        btnReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservasActionPerformed(evt);
            }
        });
        jPanel4.add(btnReservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 140, 50));

        btnHabitaciones.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnHabitaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bed.png"))); // NOI18N
        btnHabitaciones.setText(" Habitaciones");
        btnHabitaciones.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnHabitaciones.setContentAreaFilled(false);
        btnHabitaciones.setFocusPainted(false);
        btnHabitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHabitacionesActionPerformed(evt);
            }
        });
        jPanel4.add(btnHabitaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 140, 50));

        btnUsuarios.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/users_group_customers_clients_icon-icons.com_72448.png"))); // NOI18N
        btnUsuarios.setText("   Usuarios");
        btnUsuarios.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnUsuarios.setContentAreaFilled(false);
        btnUsuarios.setFocusPainted(false);
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        jPanel4.add(btnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 140, 50));

        btnReportes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/chart.png"))); // NOI18N
        btnReportes.setText("   Reportes");
        btnReportes.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnReportes.setContentAreaFilled(false);
        btnReportes.setFocusPainted(false);
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });
        jPanel4.add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 140, 50));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 420));

        panelContenedor.setBackground(new java.awt.Color(204, 204, 204));
        panelContenedor.setLayout(new java.awt.CardLayout());
        getContentPane().add(panelContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 640, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        // TODO add your handling code here:
        
        btnDashboard.addActionListener(e -> cardLayout.show(panelContenedor, "dashboard"));
       
        btnDashboard.setBorder(null);             // elimina cualquier borde
        btnDashboard.setBorderPainted(false);     // evita que el borde se pinte
        btnDashboard.setFocusPainted(false);      // elimina el borde azul de enfoque
        btnDashboard.setContentAreaFilled(false); // fondo transparente
        btnDashboard.setOpaque(false);            // evita que se pinte un fondo solido
        btnDashboard.setFocusable(false);         // evita que reciba enfoque y muestre líneas
        btnDashboard.setFocusable(false);



    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservasActionPerformed
        // TODO add your handling code here:
        
        btnReservas.addActionListener(e -> cardLayout.show(panelContenedor, "reservas"));
        
        btnReservas.setBorder(null);             // elimina cualquier borde
        btnReservas.setBorderPainted(false);     // evita que el borde se pinte
        btnReservas.setFocusPainted(false);      // elimina el borde azul de enfoque
        btnReservas.setContentAreaFilled(false); // fondo transparente
        btnReservas.setOpaque(false);            // evita que se pinte un fondo solido
        btnReservas.setFocusable(false);         // evita que reciba enfoque y muestre líneas
        btnReservas.setFocusable(false);
    }//GEN-LAST:event_btnReservasActionPerformed

    private void btnHabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabitacionesActionPerformed
        // TODO add your handling code here:
        
        btnHabitaciones.addActionListener(e -> cardLayout.show(panelContenedor, "habitaciones"));
        
        btnHabitaciones.setBorder(null);             // elimina cualquier borde
        btnHabitaciones.setBorderPainted(false);     // evita que el borde se pinte
        btnHabitaciones.setFocusPainted(false);      // elimina el borde azul de enfoque
        btnHabitaciones.setContentAreaFilled(false); // fondo transparente
        btnHabitaciones.setOpaque(false);            // evita que se pinte un fondo solido
        btnHabitaciones.setFocusable(false);         // evita que reciba enfoque y muestre líneas
        btnHabitaciones.setFocusable(false);
    }//GEN-LAST:event_btnHabitacionesActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        // TODO add your handling code here:
        
        btnUsuarios.addActionListener(e -> cardLayout.show(panelContenedor, "usuarios"));
        
        btnUsuarios.setBorder(null);             // elimina cualquier borde
        btnUsuarios.setBorderPainted(false);     // evita que el borde se pinte
        btnUsuarios.setFocusPainted(false);      // elimina el borde azul de enfoque
        btnUsuarios.setContentAreaFilled(false); // fondo transparente
        btnUsuarios.setOpaque(false);            // evita que se pinte un fondo solido
        btnUsuarios.setFocusable(false);         // evita que reciba enfoque y muestre líneas
        btnUsuarios.setFocusable(false);
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        // TODO add your handling code here:
        
        btnReportes.addActionListener(e -> cardLayout.show(panelContenedor, "reportes"));
        
        btnReportes.setBorder(null);             // elimina cualquier borde
        btnReportes.setBorderPainted(false);     // evita que el borde se pinte
        btnReportes.setFocusPainted(false);      // elimina el borde azul de enfoque
        btnReportes.setContentAreaFilled(false); // fondo transparente
        btnReportes.setOpaque(false);            // evita que se pinte un fondo solido
        btnReportes.setFocusable(false);         // evita que reciba enfoque y muestre líneas
        btnReportes.setFocusable(false);
    }//GEN-LAST:event_btnReportesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnHabitaciones;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnReservas;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel panelContenedor;
    // End of variables declaration//GEN-END:variables
}
