/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Panels;

import Charts.GraficoDashboard;
import Charts.GraficoPastelDashboard;
import org.jfree.chart.ChartPanel;
import java.awt.BorderLayout;

/**
 *
 * @author Administrator
 */
public class PanelDashboard extends javax.swing.JPanel {

    /**
     * Creates new form PanelDashboard
     */
    public PanelDashboard() {
        initComponents();
        
        // Gráfico de barras
    GraficoDashboard gd = new GraficoDashboard();
    ChartPanel cp = gd.crearPanelGraficoReservas();
    panelgrafico.setLayout(new BorderLayout());
    panelgrafico.add(cp, BorderLayout.CENTER);
    panelgrafico.validate();

    // Gráfico de pastel
    GraficoPastelDashboard gpd = new GraficoPastelDashboard();
    ChartPanel cpPastel = gpd.crearPanelGraficoPastel();
    panelgrafico2.setLayout(new BorderLayout());
    panelgrafico2.add(cpPastel, BorderLayout.CENTER);
    panelgrafico2.validate();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblUsuariosNum = new javax.swing.JLabel();
        lblUsuariosTitulo = new javax.swing.JLabel();
        lblRegistrosNum = new javax.swing.JLabel();
        lblRegistrosTitulo = new javax.swing.JLabel();
        lblingresosNum = new javax.swing.JLabel();
        lblIngresosTitulo = new javax.swing.JLabel();
        lblUsuariosNuevosNum = new javax.swing.JLabel();
        lblUsuariosNuevosTitulo = new javax.swing.JLabel();
        panelgrafico = new javax.swing.JPanel();
        panelgrafico2 = new javax.swing.JPanel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsuariosNum.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblUsuariosNum.setText("   0");
        jPanel2.add(lblUsuariosNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, 80));

        lblUsuariosTitulo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblUsuariosTitulo.setText("Usuarios registrados");
        jPanel2.add(lblUsuariosTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 110, -1));

        lblRegistrosNum.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblRegistrosNum.setText("   0");
        jPanel2.add(lblRegistrosNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 80, 80));

        lblRegistrosTitulo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblRegistrosTitulo.setText("Total Registros");
        jPanel2.add(lblRegistrosTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

        lblingresosNum.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblingresosNum.setText("   0");
        jPanel2.add(lblingresosNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 80, 80));

        lblIngresosTitulo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblIngresosTitulo.setText("Total Ingresos");
        jPanel2.add(lblIngresosTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, -1, -1));

        lblUsuariosNuevosNum.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblUsuariosNuevosNum.setText("   0");
        jPanel2.add(lblUsuariosNuevosNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 80, 80));

        lblUsuariosNuevosTitulo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblUsuariosNuevosTitulo.setText("Usuarios Nuevos del Mes");
        jPanel2.add(lblUsuariosNuevosTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 560, 120));

        panelgrafico.setBackground(new java.awt.Color(255, 255, 255));
        panelgrafico.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                panelgraficoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        panelgrafico.setLayout(new java.awt.BorderLayout());
        jPanel1.add(panelgrafico, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 270, 270));

        panelgrafico2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(panelgrafico2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 260, 270));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void panelgraficoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_panelgraficoAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_panelgraficoAncestorAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblIngresosTitulo;
    private javax.swing.JLabel lblRegistrosNum;
    private javax.swing.JLabel lblRegistrosTitulo;
    private javax.swing.JLabel lblUsuariosNuevosNum;
    private javax.swing.JLabel lblUsuariosNuevosTitulo;
    private javax.swing.JLabel lblUsuariosNum;
    private javax.swing.JLabel lblUsuariosTitulo;
    private javax.swing.JLabel lblingresosNum;
    private javax.swing.JPanel panelgrafico;
    private javax.swing.JPanel panelgrafico2;
    // End of variables declaration//GEN-END:variables
}
